import { Code, Smartphone, Layers, Database, Globe, Package, TestTube, Wrench } from "lucide-react";


export interface SkillCategory {
  title: string;
  icon: React.ElementType; // 👈 for dynamic JSX rendering
  color: string;
  skills: Skill[];
}

 export const topSkills = ["Flutter","Kotlin", "MVVM",  "Bloc", "Team Leadership"]

export interface Skill {
    name: string
    level: number
    category: string
  }
export const skillsData = [
  {
    id: "programming",
    title: "Programming Languages",
    icon: Code,
    color: "bg-gradient-to-br from-blue-500 to-blue-600",
    skills: [
      {
        name: "Java",
        level: 90,
        xp: 2700,
        maxXp: 3000,
        description: "Core language for Android development",
        category: "Language",
        rarity: "epic",
        achievements: ["Java Guru"],
      },
      {
        name: "Kotlin",
        level: 95,
        xp: 2850,
        maxXp: 3000,
        description: "Modern Android-first language",
        category: "Language",
        rarity: "legendary",
        achievements: ["Kotlin Expert"],
      },
      {
        name: "Flutter",
        level: 88,
        xp: 2640,
        maxXp: 3000,
        description: "Cross-platform UI toolkit",
        category: "Framework",
        rarity: "epic",
        achievements: ["Flutter Architect"],
      },
    ],
  },
  {
    id: "mobile",
    title: "Mobile Apps",
    icon: Smartphone,
    color: "bg-gradient-to-br from-green-500 to-green-600",
    skills: [
      {
        name: "Android SDK",
        level: 92,
        xp: 2760,
        maxXp: 3000,
        description: "Core tools for Android development",
        category: "SDK",
        rarity: "legendary",
        achievements: ["SDK Master"],
      },
      {
        name: "Material Design",
        level: 85,
        xp: 2550,
        maxXp: 3000,
        description: "Google's UI design system",
        category: "UI",
        rarity: "epic",
        achievements: ["UI Craftsman"],
      },
      {
        name: "Jetpack Components",
        level: 91,
        xp: 2730,
        maxXp: 3000,
        description: "Modern libraries for Android architecture",
        category: "Framework",
        rarity: "legendary",
        achievements: ["Jetpack Wizard"],
      },
      {
        name: "Android Studio",
        level: 90,
        xp: 2700,
        maxXp: 3000,
        description: "Primary IDE for Android development",
        category: "Tool",
        rarity: "epic",
        achievements: ["IDE Expert"],
      },
    ],
  },
  {
    id: "architecture",
    title: "Architecture & Patterns",
    icon: Layers,
    color: "bg-gradient-to-br from-purple-500 to-purple-600",
    skills: [
      {
        name: "MVVM",
        level: 90,
        xp: 2700,
        maxXp: 3000,
        description: "Model-View-ViewModel pattern",
        category: "Architecture",
        rarity: "epic",
        achievements: ["MVVM Pro"],
      },
      {
        name: "MVP",
        level: 85,
        xp: 2550,
        maxXp: 3000,
        description: "Model-View-Presenter pattern",
        category: "Architecture",
        rarity: "rare",
        achievements: ["MVP Architect"],
      },
      {
        name: "MVC",
        level: 80,
        xp: 2400,
        maxXp: 3000,
        description: "Classic Model-View-Controller pattern",
        category: "Architecture",
        rarity: "rare",
        achievements: ["MVC Master"],
      },
      {
        name: "Kotlin Coroutines",
        level: 88,
        xp: 2640,
        maxXp: 3000,
        description: "Simplified async programming",
        category: "Concurrency",
        rarity: "epic",
        achievements: ["Coroutine Commander"],
      },
    ],
  },
  {
    id: "tools",
    title: "Libraries & Tools",
    icon: Database,
    color: "bg-gradient-to-br from-orange-500 to-orange-600",
    skills: [
      {
        name: "Room DB",
        level: 85,
        xp: 2550,
        maxXp: 3000,
        description: "SQLite abstraction library",
        category: "Database",
        rarity: "epic",
        achievements: ["Room Resident"],
      },
      {
        name: "Firebase Database",
        level: 82,
        xp: 2460,
        maxXp: 3000,
        description: "Real-time cloud NoSQL database",
        category: "Database",
        rarity: "rare",
        achievements: ["Realtime Hero"],
      },
      {
        name: "Retrofit",
        level: 90,
        xp: 2700,
        maxXp: 3000,
        description: "Type-safe HTTP client",
        category: "Networking",
        rarity: "legendary",
        achievements: ["API Tamer"],
      },
      {
        name: "Dagger/Hilt",
        level: 87,
        xp: 2610,
        maxXp: 3000,
        description: "Dependency Injection frameworks",
        category: "DI",
        rarity: "epic",
        achievements: ["Injector Master"],
      },
      {
        name: "Jetpack Compose",
        level: 80,
        xp: 2400,
        maxXp: 3000,
        description: "Modern Android UI toolkit",
        category: "UI",
        rarity: "epic",
        achievements: ["Compose Crafter"],
      },
      {
        name: "Git & Bitbucket",
        level: 88,
        xp: 2640,
        maxXp: 3000,
        description: "Version control tools",
        category: "VCS",
        rarity: "epic",
        achievements: ["Version King"],
      },
      {
        name: "Gradle",
        level: 86,
        xp: 2580,
        maxXp: 3000,
        description: "Build automation tool",
        category: "Build",
        rarity: "epic",
        achievements: ["Build Wizard"],
      },
      {
        name: "Firebase Crashlytics",
        level: 83,
        xp: 2490,
        maxXp: 3000,
        description: "Crash reporting and diagnostics",
        category: "Monitoring",
        rarity: "rare",
        achievements: ["Crash Catcher"],
      },
      {
        name: "JUnit & Mockito",
        level: 84,
        xp: 2520,
        maxXp: 3000,
        description: "Unit testing libraries",
        category: "Testing",
        rarity: "rare",
        achievements: ["Test Ninja"],
      },
    ],
  },
]
